# Generated by Django 5.2.7 on 2025-10-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_autor', models.TextField()),
                ('nacionalidade', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.TextField(unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editoras',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome_editora', models.TextField(unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsbnLivro',
            fields=[
                ('id_isbn', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_isbn', models.TextField(unique=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('pais_publicacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isbn_livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.TextField()),
            ],
            options={
                'db_table': 'itens_venda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('preco', models.TextField(blank=True, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivrosAutores',
            fields=[
                ('id_livro_autor', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contribuicao', models.TextField(blank=True, null=True)),
                ('ordem_autoria', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livros_autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('valor_total', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
    ]
